  
site_name: Projectile Arcs - Documentation

pages:
    - Home: index.md
    - Getting Started:
        - Setting Up Input: GettingStarted.md
        - Radial Menu Settings: CustomizingArcs.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django